# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - run: git fetch --prune --unshallow
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install prerequisites
      run: |
        yarn

    - name: Build
      run: |
        cp .env.template .env
        yarn build-dev
        yarn build-prod

    - name: Prepare assets
      run: |
        cd dist
        curl -L -o assets.zip https://github.com/Smithsonian/dpo-voyager/releases/download/v0.7.0/voyager-demo-assets.zip
        unzip assets.zip
        rm -rf assets.zip
        
    - name: Debug
      run: |
        sudo npm install tree-node-cli -g
        treee dist

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist

